import jsPDF from 'jspdf';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from 'docx';
import { saveAs } from 'file-saver';

/**
 * Export utilities for professional PDF and DOCX generation
 */

// ──────────────────────────────────────────────────────────────────────────────
// PDF EXPORT with professional academic formatting
// ──────────────────────────────────────────────────────────────────────────────
export async function exportToPDF(sections, topic, language, pages, wordCount) {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPos = margin;

  // Helper to add new page if needed
  function checkNewPage(requiredHeight = 15) {
    if (yPos + requiredHeight > pageHeight - margin) {
      pdf.addPage();
      yPos = margin;
      return true;
    }
    return false;
  }

  // Helper to add wrapped text
  function addWrappedText(text, fontSize, fontStyle = 'normal', maxWidth = contentWidth) {
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', fontStyle);
    const lines = pdf.splitTextToSize(text, maxWidth);
    
    for (let i = 0; i < lines.length; i++) {
      checkNewPage();
      pdf.text(lines[i], margin, yPos);
      yPos += fontSize * 0.4; // Line height
    }
    return yPos;
  }

  // ── TITLE PAGE ──
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  yPos = 60;
  const titleLines = pdf.splitTextToSize(topic, contentWidth - 40);
  titleLines.forEach(line => {
    pdf.text(line, pageWidth / 2, yPos, { align: 'center' });
    yPos += 10;
  });

  yPos += 20;
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Case Study Report', pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 40;
  pdf.setFontSize(11);
  const metadata = [
    `Language: ${language}`,
    `Pages: ${pages}`,
    `Word Count: ~${wordCount.toLocaleString()}`,
    `Generated: ${new Date().toLocaleDateString()}`
  ];
  metadata.forEach(line => {
    pdf.text(line, pageWidth / 2, yPos, { align: 'center' });
    yPos += 6;
  });

  // Add footer to title page
  pdf.setFontSize(9);
  pdf.setTextColor(128, 128, 128);
  pdf.text('Generated by CaseCraft AI', pageWidth / 2, pageHeight - 15, { align: 'center' });

  // ── NEW PAGE FOR CONTENT ──
  pdf.addPage();
  yPos = margin;
  pdf.setTextColor(0, 0, 0); // Reset to black

  // ── TABLE OF CONTENTS ──
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Table of Contents', margin, yPos);
  yPos += 15;

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  sections.forEach((section, index) => {
    checkNewPage();
    pdf.text(`${index + 1}. ${section.label}`, margin + 5, yPos);
    yPos += 6;
  });

  yPos += 10;

  // ── SECTIONS ──
  sections.forEach((section, index) => {
    checkNewPage(25);
    
    // Section number and title
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`${index + 1}. ${section.label}`, margin, yPos);
    yPos += 10;

    // Section content
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    
    // Split into paragraphs and add proper spacing
    const paragraphs = section.body.split('\n\n');
    paragraphs.forEach(para => {
      if (para.trim()) {
        addWrappedText(para.trim(), 11);
        yPos += 6; // Paragraph spacing
      }
    });
    
    yPos += 8; // Section spacing
  });

  // ── FOOTER ON EACH PAGE ──
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    if (i > 1) { // Skip footer on title page
      pdf.text(`Page ${i - 1}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
    }
  }

  // Generate filename and download
  const slug = topic.replace(/\s+/g, '-').toLowerCase().slice(0, 50);
  pdf.save(`case-study-${slug}.pdf`);
}

// ──────────────────────────────────────────────────────────────────────────────
// DOCX EXPORT with professional academic formatting
// ──────────────────────────────────────────────────────────────────────────────
export async function exportToDOCX(sections, topic, language, pages, wordCount) {
  const children = [];

  // ── TITLE SECTION ──
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: topic,
          bold: true,
          size: 32, // 16pt
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: "Case Study Report",
          size: 24, // 12pt
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Language: ${language} | Pages: ${pages} | Words: ~${wordCount.toLocaleString()}`,
          size: 20, // 10pt
          italics: true,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated on ${new Date().toLocaleDateString()}`,
          size: 18, // 9pt
          color: "666666",
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 800 },
    }),
    
    // Page break
    new Paragraph({
      children: [new TextRun({ text: "", break: 1 })],
      pageBreakBefore: true,
    }),

    // ── TABLE OF CONTENTS ──
    new Paragraph({
      children: [
        new TextRun({
          text: "Table of Contents",
          bold: true,
          size: 28, // 14pt
        }),
      ],
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 300 },
    }),
  );

  // TOC entries
  sections.forEach((section, index) => {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `${index + 1}. ${section.label}`,
            size: 20, // 10pt
          }),
        ],
        spacing: { after: 100 },
        indent: { left: 200 },
      })
    );
  });

  // Page break before content
  children.push(
    new Paragraph({
      children: [new TextRun({ text: "", break: 1 })],
      pageBreakBefore: true,
    })
  );

  // ── SECTIONS ──
  sections.forEach((section, index) => {
    // Section heading
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `${index + 1}. ${section.label}`,
            bold: true,
            size: 24, // 12pt
          }),
        ],
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400, after: 200 },
      })
    );

    // Section content paragraphs
    const paragraphs = section.body.split('\n\n');
    paragraphs.forEach(para => {
      if (para.trim()) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: para.trim(),
                size: 22, // 11pt
              }),
            ],
            spacing: { after: 200 },
            alignment: AlignmentType.JUSTIFIED,
            indent: { firstLine: 200 }, // First line indent
          })
        );
      }
    });
  });

  // Create document
  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1440,    // 1 inch
              bottom: 1440,
              left: 1440,
              right: 1440,
            },
          },
        },
        children: children,
      },
    ],
    title: topic,
    creator: "CaseCraft AI",
    description: `Case study on ${topic}`,
  });

  // Generate and download
  const blob = await Packer.toBlob(doc);
  const slug = topic.replace(/\s+/g, '-').toLowerCase().slice(0, 50);
  saveAs(blob, `case-study-${slug}.docx`);
}